language: r
sudo: false
cache: packages
latex: false

r:
  - release

r_packages:
  - nlme

addons:
  apt:
    packages:
      - libmagick++-dev

warnings_are_errors: true

os:
  - linux
  - osx
pandoc: false
