language: r
root: false
cache: packages
latex: false

r:
  - release

compiler:
  - gcc

addons:
  apt:
    packages:
      - libmagick++-dev

warnings_are_errors: true

os:
  - linux
  - osx
pandoc: false
