language: r
sudo: false
cache: packages
latex: false

r:
  - release
  - [if $TRAVIS_OS_NAME = linux]; then r-devel; fi; 

r_packages:
  - nlme

addons:
  apt:
    packages:
      - libmagick++-dev

warnings_are_errors: true

os:
  - linux
  - osx
pandoc: false
