language: r
sudo: false
cache: packages
latex: false

r:
  - release

r_packages:
  - nlme

# to avoid building vignettes which takes too long
r_check_args: "--no-build-vignettes --ignore-vignettes"

addons:
  apt:
    packages:
      - libmagick++-dev

warnings_are_errors: true

os:
  - linux
  - osx
pandoc: false
