language: r
sudo: false
cache: packages
latex: false

r:
  - release
  - devel

r_packages:
  - nlme

addons:
  apt:
    packages:
      - libmagick++-dev

warnings_are_errors: true

os:
  - linux
  - osx
  - windows
pandoc: false
