language: r
dist: bionic
sudo: false
cache: packages

r:
  - release

r_packages:
  - nlme
  - devtools

# to avoid building vignettes which takes too long
r_check_args: "--no-build-vignettes --ignore-vignettes"
r_build_args: "--no-build-vignettes --ignore-vignettes"

addons:
  apt:
    packages:
      - libmagick++-dev

warnings_are_errors: true

os:
  - linux
  - osx
pandoc: true
